---
# Service account for preventing API access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: no-access-sa
---
# Service account for accessing secrets API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-access-sa
